### ISSUE TITLE
Manual del programador

### ISSUE THREAD

**Issue by far0010** [far0010/GESPRO_GESTIONTAREAS#29]
- Instalación Android Studio
- Importación del proyecto
- Estructura directorios
- Ejecución tests en local
- Servicios de integración continua
- Creación de un ejecutable
- Plataforma de desarrollo del algoritmo
- Plataforma de conteo

**Comment by fps1001** [comment]
davidmigloz added a commit that referenced this issue on 3 Feb 2017
@davidmigloz
Add javadoc #151

**Comment by fps1001** [comment]
davidmigloz added a commit that referenced this issue on 5 Feb 2017
@davidmigloz
Document Manual Programador #151

**Comment by fps1001** [comment]
davidmigloz added a commit that referenced this issue on 7 Feb 2017
@davidmigloz
Convert annex C to latex #151
