### ISSUE TITLE
Grabar discos

### ISSUE THREAD

**Issue by fps1001** [far0010/GESPRO_GESTIONTAREAS#39]
- Código fuente app
- Ejecutable app
- Herramientas
     -    Plataforma de desarrollo del algoritmo
     -    Herramienta de conteo de abejas
- Documentación
     -    Memoria
     -    Anexos
     -    JavaDoc
- Dataset de videos

**README**

- Repositorio GoBees
- Repositorio prototipos
- Repositorio dependencia OpenCV

**Comment by far0010** [comment]
davidmigloz added a commit that referenced this issue on 1 Feb 2017
@davidmigloz
Add cd cover #173

**Comment by far0010** [comment]
davidmigloz added a commit that referenced this issue on 1 Feb 2017
@davidmigloz
Add cd cover #173

**Comment by far0010** [comment]
@davidmigloz davidmigloz closed this on 10 Feb 2017

**Comment by far0010** [comment]
@jaciperez jaciperez mentioned this issue on 16 Mar
Grabar discos Guillehf01/go-bees#46
