### ISSUE TITLE
Permitir notas multilinea

### ISSUE THREAD

**Issue by fps1001** [far0010/GESPRO_GESTIONTAREAS#7]

**Comment by far0010** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Design-team-61952f5af2df49001488d9a9/issues/far0010/GESPRO_GESTIONTAREAS/7?planning-poker) with ZenHub @fps1001

**Comment by fps1001** [comment]
davidmigloz added a commit that referenced this issue on 22 Jan 2017
@davidmigloz
Allow multiline notes #169
